-- MySQL Script generated by MySQL Workbench
-- Tue May 31 01:00:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema notificaciondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema notificaciondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `notificaciondb` DEFAULT CHARACTER SET utf8 ;
USE `notificaciondb` ;

-- -----------------------------------------------------
-- Table `notificaciondb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NULL,
  `apellidos` VARCHAR(200) NULL,
  `dni` VARCHAR(50) NULL,
  `celular` INT NULL,
  `celular2` INT NULL,
  `correo` VARCHAR(50) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  INDEX `fk_persona_rol1_idx` (`rol_idrol` ASC)  ,
  CONSTRAINT `fk_persona_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `notificaciondb`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`proceso` (
  `idproceso` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `fech_creacion` DATETIME NULL,
  `tipo` VARCHAR(80) NULL,
  `descripcion` VARCHAR(1000) NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idproceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`audiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`audiencia` (
  `idaudiencia` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(80) NULL,
  `fecha` DATETIME NULL,
  `hora` DATETIME NULL,
  `edificio` VARCHAR(100) NULL,
  `direccion` VARCHAR(1000) NULL,
  `sala` VARCHAR(45) NULL,
  `observacion` VARCHAR(1000) NULL,
  `proceso_idproceso` INT NOT NULL,
  PRIMARY KEY (`idaudiencia`),
  INDEX `fk_audiencia_proceso1_idx` (`proceso_idproceso` ASC)  ,
  CONSTRAINT `fk_audiencia_proceso1`
    FOREIGN KEY (`proceso_idproceso`)
    REFERENCES `notificaciondb`.`proceso` (`idproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`notificacion` (
  `idnotificacion` INT NOT NULL AUTO_INCREMENT,
  `proceso_idproceso` INT NOT NULL,
  `audiencia_idaudiencia` INT NOT NULL,
  PRIMARY KEY (`idnotificacion`),
  INDEX `fk_notificacion_proceso1_idx` (`proceso_idproceso` ASC)  ,
  INDEX `fk_notificacion_audiencia1_idx` (`audiencia_idaudiencia` ASC)  ,
  CONSTRAINT `fk_notificacion_proceso1`
    FOREIGN KEY (`proceso_idproceso`)
    REFERENCES `notificaciondb`.`proceso` (`idproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacion_audiencia1`
    FOREIGN KEY (`audiencia_idaudiencia`)
    REFERENCES `notificaciondb`.`audiencia` (`idaudiencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `correo` VARCHAR(100) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `notificaciondb`.`persona_has_proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `notificaciondb`.`persona_has_proceso` (
  `persona_idpersona` INT NOT NULL,
  `proceso_idproceso` INT NOT NULL,
  PRIMARY KEY (`persona_idpersona`, `proceso_idproceso`),
  INDEX `fk_persona_has_proceso_proceso1_idx` (`proceso_idproceso` ASC)  ,
  INDEX `fk_persona_has_proceso_persona_idx` (`persona_idpersona` ASC)  ,
  CONSTRAINT `fk_persona_has_proceso_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `notificaciondb`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_persona_has_proceso_proceso1`
    FOREIGN KEY (`proceso_idproceso`)
    REFERENCES `notificaciondb`.`proceso` (`idproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
